apiVersion: v1
kind: Service
metadata:
  name: python-test-service
spec:
  type: NodePort
  selector:
    app: python-test-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007   # You can pick any free port between 30000-32767